name:                nix-mirror
version:             0.1.0.0
github:              "alexoundos/nix-mirror"
license:             GPL-3
author:              "Alexander Tomokhov"
maintainer:          "Alexander Tomokhov"
copyright:           "Alexander Tomokhov"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexoundos/nix-mirror#readme>

dependencies:
- base >= 4.7 && < 5

# internal-libraries:
#   nix-mirror-lib:
library:
  source-dirs: src
  exposed: false
  dependencies:
    - bytestring
    - conduit
    - containers
    - cryptohash-sha256
    - data-default-class
    - directory
    - http-client
    - http-types
    - req
    - req-conduit
    - safe-exceptions
    - temporary
    - text
    - vector
    - yaml

executables:
  nix-mirror-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nix-mirror
      - optparse-applicative

tests:
  nix-mirror-test:
    main:                Test.hs
    source-dirs:         test
    # other-modules:       Download
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nix-mirror
      - HsYAML
      - bytestring
      - req
      - tasty
      - tasty-hunit
      - text
