name:                nix-mirror
version:             0.1.1.1
github:              "alexoundos/nix-mirror"
license:             GPL-3
author:              "Alexander Tomokhov"
maintainer:          "Alexander Tomokhov"
copyright:           "Alexander Tomokhov"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/alexoundos/nix-mirror#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed: false
  dependencies:
    - aeson
    - base16-bytestring
    - bytestring
    - conduit
    - containers
    - cryptohash-sha1
    - cryptohash-sha256
    - cryptohash-sha512
    - directory
    - filepath
    - http-client
    - http-types
    - mtl
    - req
    - req-conduit
    - safe-exceptions
    - temporary
    - typed-process
    - text
    - vector
    - yaml

executables:
  nix-mirror:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nix-mirror
      - directory
      - mtl
      - optparse-applicative
      - safe-exceptions
      - text

tests:
  nix-mirror-test:
    main:                Test.hs
    source-dirs:         test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - nix-mirror
      - bytestring
      - req
      - tasty
      - tasty-hunit
      - text
      - yaml
